language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.301
services:
  - docker
script:
- dotnet restore TestDocker.csproj
- dotnet build TestDocker.csproj
- docker build -t vertygo/testdocker .
- docker tag vertygo/testdocker:latest
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push vertygo/testdocker:latest
