version: 1.0.{build}
image: Visual Studio 2017
environment:
  DOCKER_USER:
    secure: ozABIPjQgbSATvzfe8ib+w==
  DOCKER_PASS:
    secure: sxD1Yw1lkwYqX8rowyloHSJCMwZYnxhJZDlTU3dWV+KlfT1J6eJe1h8/ncbDsCMj

services:
- docker

install:
  - nuget restore

build_script:
  - msbuild TestDocker.sln /t:Build /p:Configuration=Release
  - docker tag testdockerfullframework r.cfcr.io/vertygo/testdockerfullframework

deploy_script:
  - docker images
  - ps: echo $env:DOCKER_PASS | docker login -u="$env:DOCKER_USER" r.cfcr.io --password-stdin
  - docker push r.cfcr.io/vertygo/testdockerfullframework