version: 1.0.{build}
image: Visual Studio 2017
environment:
  DOCKER_USER:
    secure: lE8GCxONKoCsPhdTOE2uZw==
  DOCKER_PASS:
    secure: euDyH/qKlvolmOvjNCWggg==

services:
- docker

install:
  - nuget restore

build_script:
  - msbuild TestDocker.sln
  - docker build -t testdockerfullframework TestDockerFullFramework
  - docker tag testdockerfullframework repo.treescale.com/vertygo/testdockerfullframework

deploy_script:
  - ps: echo $env:DOCKER_PASS | docker login -u="$env:DOCKER_USER" repo.treescale.com --password-stdin
  - docker push repo.treescale.com/Vertygo/testdockerfullframework