name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  config: Release
  disable_test_parallelization: true

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Run SQL Container
      run: docker compose up -d

    - name: Test
      run: dotnet test ./PersistenceTests
